---
title: "Interest Rate Modelling"
author: Rancy_Chepchirchir
output: html_notebook
---

```{r}
library(yuima)
# Brownian Motion
m1=setModel(drift="0",diffusion="1", state.var="x",time.var="t",solve.var="x",xinit=100)
X=simulate(m1)
plot(X)
d1=X@data@original.data
d1
grid=setSampling(Terminal=1,n=1000)
X=simulate(m1,sampling=grid)
plot(X)
```

```{r}
# Geometric BM
m1=setModel(drift="mu*s",diffusion="sigma*s", state.var="s",time.var="t",solve.var="s",xinit=100)
X=simulate(m1,true.param=list(mu=0.1,sigma=0.2))
plot(X)
# Prob distr associated with the GBM
m1=setModel(drift="mu*s",diffusion="sigma*s", state.var="s",time.var="t",solve.var="s",xinit=100)
simnum=100
dist=c(.31, .52,0.6,0.7, .95)
newsim=function(i){simulate(m1,true.param=list(mu=0.1,sigma=0.2))@data@original.data}
newsim(1)
sim=sapply(1:simnum,function(x)newsim(x))
m2=t(sim)
m2
apply(m2,2,mean)
tile=sapply(1:100,function(x)quantile(m2[,x], dist) )
tile
```
```{r}
# Vasicek Model
m1 = setModel(drift = "theta*(mu-x)", diffusion = "sigma", state.var = "x", 
    time.var = "t", solve.var = "x", xinit = 0.5)
X = simulate(m1, true.param = list(mu = 0.5, sigma = 0.2, 
    theta = 2))
plot(X)
# CIR Model
m1 = setModel(drift = "theta*(mu-x)", diffusion = "sigma*(x^0.5)", state.var = "x", 
    time.var = "t", solve.var = "x", xinit = 0.5)
X = simulate(m1, true.param = list(mu = 0.5, sigma = 0.2, 
    theta = 2))
plot(X)
# CKLS MOdel
grid=setSampling(Terminal=1, n=1000)
m1 = setModel(drift = "alpha1+(alpha2*x)", diffusion = "alpha3*(x^alpha4)", state.var = "x", 
    time.var = "t", solve.var = "x", xinit = 0.5)
X = simulate(m1, true.param = list(alpha1 = 0.1, alpha2 = 0.2, alpha3 = 0.3,
    alpha4 = 0.4), sampling=grid)
plot(X)
# Hyperbolic Processes
m1 = setModel(drift = "-theta*x/((1+x^2)^0.5)", diffusion = "1", state.var = "x", 
    time.var = "t", solve.var = "x", xinit = 0.5)
X = simulate(m1, true.param = list(theta = 1))
plot(X)
```
```{r}
# Fitting SDE to given data
library(Ecdat)
data (Irates)
rates <-Irates[,'r1']
plot(rates)
X<-window(rates, start=1964.471, end=1989.333)
m1 = setModel(drift = "theta*(mu-x)", diffusion = "sigma", state.var = "x", 
    time.var = "t", solve.var = "x", xinit = 0.5)
X = simulate(m1, true.param = list(mu=0.1, sigma=0.2, theta=2))
initialise=list(mu=0.05, sigma=0.5, theta=1)
lowbound=list(mu=0, sigma=0, theta=0)
upbound=list(mu=0.2, sigma=2, theta=3)
mle=qmle(X, start=initialise, lower=lowbound, upper=upbound)
summary(mle)
# Incorporating Jumps into the SDE
library(yuima)
grid=setSampling(Terminal=1, n=1000)
jump=list(intensity="7", df=list("dnorm(z, 0, 0.2)"))
m1 = setModel(drift = "theta*(mu-x)", diffusion = "sigma", state.var = "x", 
    time.var = "t", solve.var = "x", xinit = 0.2, jump.coeff="1", 
    measure=jump, measure.type="CP")
X = simulate(m1, true.param = list(mu=0.1, sigma=0.2, theta=2), sampling=grid)
plot(X)
```
```{r}
# Fractional Brownian Motion
grid=setSampling(Terminal=1, n=1000)
m1 = setModel(drift = "theta*(mu-x)", diffusion = "sigma", state.var = "x", 
    time.var = "t", solve.var = "x", xinit = 0.2, hurst= 0.3)
m2 = setModel(drift = "theta*(mu-x)", diffusion = "sigma", state.var = "x", 
    time.var = "t", solve.var = "x", xinit = 0.2, hurst= 0.7)
X = simulate(m1, true.param = list(mu=0.1, sigma=0.2, theta=2), sampling=grid)
Y = simulate(m2, true.param = list(mu=0.1, sigma=0.2, theta=2), sampling=grid)
par(mfrow=c(2, 1)); plot(X); plot(Y)
# Correlated BMs
solution=c("x1", "x2", "x3")
drift=c("b1*x1", "b2*x2", "b3*x3")
c1=c(2, 1, 3, 1, 4, 2, 3, 2, 5)
cov=matrix(c1, 3, 3)
cov==t(cov); chol=chol(cov); diff=chol; diff
m1 = setModel(drift = drift, diffusion = diff, solve.variable = solution, 
     xinit = c(1, 2, 3)) 
X = simulate(m1, true.param = list(b1=0.5, b2=0.6, b3=0.7))
plot(X)
```
```{r}
# Multidimensional BM (Hull-White 2-factor Model)
solution =c("r","u")
drift=c("theta-(alpha*r)+u","-b*u")
c1=c("sigma1","0","0","sigma2")
diff=matrix(c1,2,2)
m1=setModel(drift=drift,diffusion=diff,
solve.variable=solution,xinit=c(0.1,0.2))
X=simulate(m1,true.param=list(theta=1,alpha=1,b=1,sigma1=2,sigma2=2))
plot(X)
# Heston Model
solution =c("s1","s2")
drift=c("mu*s1","k*(theta-s2)")
d2=c("c1*s1*(s2^{0.5})","c2*s1*(s2^(0.5))","0","c3*eta*(s2^(0.5))")
diff=matrix(d2,byrow=T,2)
cov=matrix(c(2,0.7,0.7,5),2,2)
cov;chol(cov); 
m1=setModel(drift=drift,diffusion=diff,
solve.variable=solution,xinit=c(50,5))
X=simulate(m1,true.param=list(theta=1,eta=1,mu=1,k =2,
c1=chol(cov)[1,1],c2=chol(cov)[1,2],c3=chol(cov)[2,2]))
plot(X)
```
References:
Maria, S I. (2012) The yuima package: an R framework for simulation and inference of stochastic differential equations: Department of Economics, Business and Statistics University of Milan, Milan, Italy